version: '3.7'

services:
  bot:
    build: .
    volumes:
      - db-data:/app/data
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8443:8443"

  backup:
    build:
      context: .
      dockerfile: Dockerfile.backup
    volumes:
      - db-data:/app/data
    environment:
      - TZ=Europe/Moscow

volumes:
  db-data:
    driver: local